trigger:
- main

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python310:
      python.version: '3.10'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install requests
  displayName: 'Install dependencies'

- script: |
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'pytest'

- task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: 'print ("Hello World")'



# (myAzurePipelineProject)
#'$(System.DefaultWorkingDirectory)/tests/base_pipeline_status.py'
# $(Build.SourcesDirectory)/
# '$(System.DefaultWorkingDirectory)/_myAzurePipelineProject/testpy.py'